apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounth: 
        - mountPath: /volume-no-container
          name: nome-do-volume
    - name: jenkins-container
      image: jenkins:alpine
      volumeMounth: 
        - mountPath: /volume-no-container
          name: nome-do-volume
  volume:
    - name: primeiro-volume
      hostPath:
        path: caminho-para-o-volume
        type: Directory